### ISSUE TITLE
Throwing exceptions when downloading

### ISSUE THREAD

**Issue by thesteve0** [DigitalGlobe/rdatools#1]
Tried to use rda job watch and it keeps throwing exceptions when downloading. Version 0.0.5 on windows 10 in powershell

PS E:\tmp> rda job watch \tmp\104001001B2F1000 9402988a-bcfc-4e54-b1ec-0501ddb7bcbc
 172 / 898 [==============================================>---------------------------------------------------------------------
Failed downloading all artifacts; rerun the command to pick up where you left off.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x99b9e6]

goroutine 1 [running]:
github.com/DigitalGlobe/rdatools/rda/cmd.glob..func12(0x1036400, 0xc00006b680, 0x2, 0x2, 0x0, 0x0)
        /home/youngpm/go/src/github.com/DigitalGlobe/rdatools/rda/cmd/job.go:303 +0x9b6
github.com/spf13/cobra.(*Command).execute(0x1036400, 0xc00006b620, 0x2, 0x2, 0x1036400, 0xc00006b620)
        /home/youngpm/go/src/github.com/spf13/cobra/command.go:762 +0x47a
github.com/spf13/cobra.(*Command).ExecuteC(0x10368c0, 0x1, 0x1, 0x1037e20)
        /home/youngpm/go/src/github.com/spf13/cobra/command.go:852 +0x304
github.com/spf13/cobra.(*Command).Execute(0x10368c0, 0x405527, 0xc00005e058)
        /home/youngpm/go/src/github.com/spf13/cobra/command.go:800 +0x32
github.com/DigitalGlobe/rdatools/rda/cmd.Execute()
        /home/youngpm/go/src/github.com/DigitalGlobe/rdatools/rda/cmd/root.go:67 +0x34
main.main()
        /home/youngpm/go/src/github.com/DigitalGlobe/rdatools/rda/main.go:28 +0x27
PS E:\tmp> rda --version
rda version 0.0.5, commit 3e822dcf3f94006cb43356a164a5fbc063503c84, built at 2018-12-14T23:33:55Z

**Comment by youngpm** [comment]
A user! Very exciting.

Looks like I was misusing https://github.com/aws/aws-sdk-go/blob/master/aws/awserr/error.go#L42

The error that was bubbled up to you must be an AWS error, but I was assuming awserr.OrigErr would return a nonnil error always, which made srcErr = nil here:  

https://github.com/DigitalGlobe/rdatools/blob/master/rda/cmd/job.go#L303

Fixing now...

**Comment by youngpm** [comment]
@thesteve0 I pushed a new release with the fix, let me know if the issue persists.

**Comment by thesteve0** [comment]
Just realized I should have started this bug report with

FIRST POST!

Thanks for fixing - will test later today
